services:
  db:
    image: postgres:15.3-alpine
    container_name: demowebflux-db
    command: postgres -c 'max_connections=250'
    restart: unless-stopped
    environment:
      POSTGRES_DB: demo_webflux
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - 5400:5432
volumes:
  postgres:
    name: demowebflux-db
    driver: local