server:
  port: 8046

spring:
  application:
    name: crypt-gate
  flyway:
    schemas: demo_webflux
    placeholder-replacement: true
    enabled: true
    user: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5400}/${DB_NAME:demo_webflux}
  r2dbc:
    pool:
      enabled: true
      initial-size: 5
      max-size: 50
      max-idle-time: 120s
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5400}/${DB_NAME:demo_webflux}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

logging:
  level:
    root: info
    com.example: debug

app:
  decimalScale: 8 # до скольки знаков после запятой округляем значения
  widgetUrl: ${WIDGET_URL:http://localhost:8047/invoice/}
  walletsMode: GENERATE # POOL | GENERATE
  rates:
    lifetimeSeconds: 30 # время жизни последнего полученного курса. дольше этого срока если не получили курса - считаем что курса нет
    updateInterval: 5000 # время между запросами курса с биржи
    supported: TRXUSDT, ETHUSDT, TRXETH # пары, которые запрашиваем с биржи
  trongrid:
    #    apikey: ${TRONGRID_API_KEY}
    updateInterval: 5000
