server:
  port: 8046

spring:
  flyway:
    schemas: demo_webflux
    placeholder-replacement: true
    enabled: true
    user: demo_webflux
    password: demo_webflux
    url: jdbc:postgresql://localhost:5432/demo_webflux
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/demo_webflux
    username: demo_webflux
    password: demo_webflux
logging:
  level:
    root: info
